---
version: "3.8"

services:
  backend:
    build: ./backend
    container_name: blogi-backend
    environment:
      - ALLOWED_ORIGIN=http://localhost:3000
      - MONGO_URI=mongodb://janne:123asd@mongodb:27017/
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - main-network
  frontend:
    build: ./frontend
    container_name: blogi-frontend
    environment:
      - REACT_APP_BACKEND_URI=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - main-network
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=janne
      - MONGO_INITDB_ROOT_PASSWORD=123asd
    container_name: mongodb
    volumes:
      - ./backend/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - main-network

networks:
  main-network:
    name: main-network