version: "3"

services: 
  backend:
    build: ./backend
    ports:
      - 8080:8080
    container_name: example-redis-backend
    networks: 
      - redis-network
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    container_name: example-redis-frontend
  redis:
    image: redis
    ports: 
      - 6379:6379
    container_name: example-redis
    restart: unless-stopped
    networks: 
      - redis-network

networks: 
  redis-network:
    name: redis-network