version: "3"

services: 
  backend:
    build: ./backend
    environment: 
      - POSTGRES_HOST=db-postgres
      - POSTGRES_USER=janne
      - POSTGRES_PASSWORD=123asd
      - POSTGRES_DATABASE=janne
    ports:
      - 8080:8080
    container_name: example-redis-backend
    depends_on: 
      - db
    networks: 
      - redis-network
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    container_name: example-redis-frontend
  redis:
    image: redis
    ports: 
      - 6379:6379
    container_name: example-redis
    restart: unless-stopped
    networks: 
      - redis-network
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=janne
      - POSTGRES_PASSWORD=123asd
    container_name: db-postgres
    ports:
      - 5432:5432
    networks: 
      - redis-network

networks: 
  redis-network:
    name: redis-network