version: "3.8"

services:
  backend:
    build: ./backend
    environment:
      - POSTGRES_HOST=2-8-db-postgres
      - POSTGRES_USER=janne
      - POSTGRES_PASSWORD=123asd
      - POSTGRES_DATABASE=janne
    ports:
      - 8080:8080
    container_name: 2-8-backend
    depends_on:
      - db
    networks:
      - redis-network
      - nginx-network
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    container_name: 2-8-frontend
    networks:
      - nginx-network
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: 2-8-redis
    restart: unless-stopped
    networks:
      - redis-network
      - nginx-network
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=janne
      - POSTGRES_PASSWORD=123asd
    container_name: 2-8-db-postgres
    ports:
      - 5432:5432
    networks:
      - redis-network
  nginx:
    image: nginx
    container_name: 2-8-nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

networks:
  redis-network:
    name: redis-network
  nginx-network:
    name: nginx-network
