version: "3"

services: 
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    networks: 
      - training-network
  backend:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    networks: 
      - training-network
    volumes: 
      - models:/src/model
    depends_on: 
      - training
  training:
    build: ./ml-kurkkumopo-training
    # ports:
    #   - 3000:3000
    networks: 
      - training-network
    volumes: 
      - models:/src/model
      - images:/src/imgs

networks: 
  training-network:
    name: training-network

volumes: 
  models:
  images: